### ISSUE TITLE
Global Site Tag

### ISSUE THREAD

**Issue by chandlervdw** [colbyfayock/gatsby-plugin-google-marketing-platform#18]
This [Tag Manager Support Doc](https://support.google.com/tagmanager/answer/7582054?hl=en) expains that the difference between Tag Manager and global site tags.

Based on what **Google Analytics** admin gives me to paste into the `<head />`, the google tag manager link looks like this: 

`<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXX"></script>`

But when I use this gatsby plugin, the `script` in the `<head />` is:

`<script async src="https://www.googletagmanager.com/gtm.js?id=GTM-XXX"></script>`
Additionally, this script passes `gaPropertyId` into the `window.dataLayer` array in the subsequent script(s). 

I can't get tracking to work using this plugin. Could it be due to this discrepancy?

**Comment by colbyfayock** [comment]
hm thats strange - i just checked my site and it's working with the latest version

here's my config: https://github.com/colbyfayock/colbyfayock/blob/master/gatsby-config.js#L33

is it not working in development mode or production mode? if it's on develop, its by default off so that it doesn't make requests to google analytics. you can change that by setting this property in options:

```
includeInDevelopment: true,
```

![image](https://user-images.githubusercontent.com/1045274/79391423-85a3e780-7f3f-11ea-80f6-6d149b13cdcb.png)
